echo "                                             .:!?JY555YJ?!^.                                     "
echo "                                           :7J5GGGPPPPGBBBBGJ^                                   "
echo "                                         :?YYY5PPPPPGGBBBBB###5^                                 "
echo "                              .......   ^?JYYY5PPPGGBBBBBBB####B!                                "
echo "                          .^~!!!!!7?7!~~????JY5GGGBBBBBBBBB######!                               "
echo "                         :~~~~~~~~!777777777!7JPPPPPPPPPPPGBBBBB#G.                              "
echo "                       .YJ~^~~~~~~~!!!!!!!!!77J55555555555GBBBBBBBPPPP7::..                      "
echo "                       !BBPJ!^~~~~~!!!!!!!7???J5YY55555555GBBBBBBB####J~!!~~:.                   "
echo "                       ?BGGBGY!^~~~!!!!77?????J55YYY555555GBBBBB######J~!!!!!!^.                 "
echo "                      .!BGGGBBGY!~~!!77??????7J5YYYYYY5555GBB#########J~~~~~~~!~:                "
echo "                  .~7?YPGGGGGGGGPY777?????????J55555555555PBBBBBBBBBBBJ!!!!!!!!!7:               "
echo "                :^~!!!!JJJJJJJJJJYPG5JJJJJJJJJ5BBBBBBBBBG555YYYYYYYYYYY555555555Y7               "
echo "              .^~~~~~~!JJJJJJJJYY5P##B5JJJJJJJ5BBBBBBBG5YJ5555YYYYYYYYY5555555J?77.              "
echo "              :^^~~~~~!JJJJJJY555YP####BPYJJJJ5BBBBBP5JJYJ555555YYYYYY555555J?7777.              "
echo "              ^^^^^~~~!JJJJY55555YP######BPYJJ5BBGPYJJYYYJ55555555YYYY5555J777777~               "
echo "              .^^^^^^~!JJY5555555YP########BPY5GPYJJJYJYYJY555555555YYYYJ7777777!.               "
echo "               .:^~~^~!Y5555555555PBBBBBBBBBBBG5YYYYYYYYYY5PP5PPP5P5PPY77777777^                 "
echo "                 .:^!7?YY5PPPPP55PGBBBBBBBBBB#B555YYYY55555PPPPPP55PB#PJJ777!~.                  "
echo "                    .:^~~~!!!~:..~JPBBBBBB####B5PP5555YJ7^^7J55PPGB###PJJ?~:.                    "
echo "                                   .^!JYGB####B55YYJ7~:      .:^~7777!^:.                        "
echo "                                           ^^^^                                                  "
echo "                                                                                                 "
echo "        :?J!     .~?JJ7~^7?J?7~^!?JJ?~..7~     ^?^     !7 :!77777~.  ^?.:!77  ^!777!^            "
echo "        .JYY!   .?YY??YYY?!7YYYY?!7JYY?.!Y^   :YJJ.   ~Y~       ^?J. !Y??~  :J?:   ::^:          "
echo "         .JYY! .?YY7 !YYJ.  !YYJ.  ~YYY. ?J. .J?.J?  :Y7  .^~!!~~7Y^ !57    JJ^:::::^Y?          "
echo "          :JYY~7YY7  !YYJ   ~YYJ.  ~YYY. .J? 7J. :Y! ?J. !J~:....!Y^ !Y:   .JJ~^^~~^^^:          "
echo "           :JYYYY7   !YYJ   ~YYY.  ~YYY.  ^Y?Y^   ~Y?Y:  ?Y:    :75^ !5:    ^J7.    :~.          "
echo "            :7JJ!    ^JJ!   :?J7   :?J7    ~J~     !J^    !77!!!~~J^ ~J:     .~777777~           "

